"""
Ablation studies for the Yorùbá OCR fine-tuning experiment.

Runs three structured ablation experiments, each isolating a single
component of the fine-tuning pipeline to quantify its contribution:

  Ablation A — Data Size
      Trains on 25%, 50%, 75%, and 100% of the training set.
      Measures how performance scales with corpus size.
      Motivates the argument for continued data collection.

  Ablation B — Character Dictionary
      Compares fine-tuning with the Yorùbá character dictionary vs
      the default English dictionary. Measures the dictionary's
      contribution to diacritic fidelity specifically.

  Ablation C — Data Augmentation
      Compares fine-tuning with RecAug (standard text recognition
      augmentation) vs without it. Measures overfitting risk on
      this small low-resource corpus.

Each ablation writes its config to experiments/ablation/{ablation_id}/,
trains a model, evaluates on val and test, and appends results to
results/tables/metrics.csv under a traceable model label.

Usage:
    # Run all ablations
    python scripts/10_ablation_study.py --ablation all

    # Run a single ablation
    python scripts/10_ablation_study.py --ablation data_size
    python scripts/10_ablation_study.py --ablation dictionary
    python scripts/10_ablation_study.py --ablation augmentation

    # Quick test with fewer epochs
    python scripts/10_ablation_study.py --ablation data_size --epochs 10
"""

from __future__ import annotations

import argparse
import json
import logging
import random
import shutil
import sys
import unicodedata
from datetime import datetime, timezone
from pathlib import Path

import yaml

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
log = logging.getLogger(__name__)

BASE_CONFIG = Path("configs/paddleocr_yoruba_rec.yml")
DATA_DIR = Path("data/processed")
PADDLE_DIR = Path("PaddleOCR")
RESULTS_CSV = Path("results/tables/metrics.csv")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_base_config() -> dict:
    """Load the base fine-tuning config generated by 03_generate_config.py."""
    if not BASE_CONFIG.exists():
        raise FileNotFoundError(
            f"{BASE_CONFIG} not found. Run 03_generate_config.py first."
        )
    with BASE_CONFIG.open(encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def save_config(cfg: dict, path: Path) -> None:
    """Write a YAML config to disk."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as fh:
        yaml.dump(cfg, fh, allow_unicode=True, default_flow_style=False, sort_keys=False)


def sample_label_file(
    src_label: Path,
    fraction: float,
    dst_label: Path,
    seed: int = 42,
) -> int:
    """
    Write a randomly sampled subset of a label file.

    Returns the number of lines written.
    """
    with src_label.open(encoding="utf-8") as fh:
        lines = [l for l in fh.readlines() if l.strip()]
    rng = random.Random(seed)
    sample = rng.sample(lines, k=max(1, int(len(lines) * fraction)))
    dst_label.parent.mkdir(parents=True, exist_ok=True)
    with dst_label.open("w", encoding="utf-8") as fh:
        fh.writelines(sample)
    return len(sample)


def run_training(config_path: Path, gpus: str, epochs: int | None) -> bool:
    """
    Invoke 04_train_paddleocr.py for a given config, returning success bool.
    """
    import subprocess

    cmd = [
        sys.executable,
        "scripts/04_train_paddleocr.py",
        "--config", str(config_path),
        "--paddle-dir", str(PADDLE_DIR),
        "--gpus", gpus,
    ]
    if epochs:
        cmd += ["--epochs", str(epochs)]

    result = subprocess.run(cmd)
    return result.returncode == 0


def run_evaluation(model_dir: Path, model_name: str, split: str) -> dict:
    """
    Invoke 05_evaluate.py for a given model dir and return the metrics dict.
    """
    import subprocess

    per_sample = Path("results/tables") / f"{model_name}_{split}.jsonl"
    cmd = [
        sys.executable,
        "scripts/05_evaluate.py",
        "--model-dir", str(model_dir),
        "--data-dir", str(DATA_DIR),
        "--split", split,
        "--model-name", model_name,
        "--results-csv", str(RESULTS_CSV),
        "--per-sample-log", str(per_sample),
    ]
    subprocess.run(cmd, check=True)

    # Return the last row appended to the CSV as a dict
    import csv
    with RESULTS_CSV.open(encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh))
    last = next((r for r in reversed(rows) if r["model"] == model_name), {})
    return last


def save_ablation_log(record: dict, log_path: Path) -> None:
    """Append an ablation run record to a JSONL log."""
    log_path.parent.mkdir(parents=True, exist_ok=True)
    with log_path.open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(record, ensure_ascii=False) + "\n")


# ---------------------------------------------------------------------------
# Ablation A — Data Size
# ---------------------------------------------------------------------------

def ablation_data_size(gpus: str, epochs: int) -> None:
    """
    Train on 25%, 50%, 75%, 100% of the training data.

    For each fraction, a sampled label file is written to
    experiments/ablation/data_size/labels_XX/train.txt, and the config
    is patched to point at that subset. Val and test splits are unchanged.
    """
    log.info("=== Ablation A: Data Size ===")
    base_cfg = load_base_config()
    full_train = DATA_DIR / "labels" / "train.txt"

    for frac in [0.25, 0.50, 0.75, 1.00]:
        label_id = f"{int(frac * 100):03d}pct"
        ablation_dir = Path("experiments/ablation/data_size") / label_id
        ablation_dir.mkdir(parents=True, exist_ok=True)

        # Sampled training labels
        sampled_label = ablation_dir / "train.txt"
        n = sample_label_file(full_train, frac, sampled_label)
        log.info("Data size %d%% — %d training samples.", int(frac * 100), n)

        # Patch config
        cfg = yaml.safe_load(yaml.dump(base_cfg))  # deep copy
        cfg["Global"]["save_model_dir"] = str(ablation_dir / "model")
        cfg["Train"]["dataset"]["label_file_list"] = [str(sampled_label.resolve())]
        config_path = ablation_dir / "config.yml"
        save_config(cfg, config_path)

        model_name = f"ablation_data_size_{label_id}"
        success = run_training(config_path, gpus, epochs)
        if not success:
            log.error("Training failed for %s. Skipping eval.", model_name)
            continue

        best_model = ablation_dir / "model" / "best_accuracy"
        for split in ("val", "test"):
            run_evaluation(best_model, f"{model_name}_{split}", split)

        log.info("Ablation A [%s] done.", label_id)


# ---------------------------------------------------------------------------
# Ablation B — Character Dictionary
# ---------------------------------------------------------------------------

def ablation_dictionary(gpus: str, epochs: int) -> None:
    """
    Compare training with the Yorùbá char dict vs the default English dict.

    The Yorùbá dict includes combining diacritics and precomposed Yorùbá
    characters. The English dict uses PaddleOCR's built-in character set,
    which lacks these. This ablation isolates the contribution of the dict.
    """
    log.info("=== Ablation B: Character Dictionary ===")
    base_cfg = load_base_config()

    configs = {
        "yoruba_dict": str(DATA_DIR / "dictionary" / "yoruba_char_dict.txt"),
        "english_dict": None,   # None = PaddleOCR default English dict
    }

    for dict_label, dict_path in configs.items():
        ablation_dir = Path("experiments/ablation/dictionary") / dict_label
        ablation_dir.mkdir(parents=True, exist_ok=True)

        cfg = yaml.safe_load(yaml.dump(base_cfg))
        cfg["Global"]["save_model_dir"] = str(ablation_dir / "model")
        if dict_path is not None:
            cfg["Global"]["character_dict_path"] = dict_path
        else:
            # Remove the key so PaddleOCR falls back to its built-in English dict
            cfg["Global"].pop("character_dict_path", None)

        config_path = ablation_dir / "config.yml"
        save_config(cfg, config_path)

        model_name = f"ablation_dict_{dict_label}"
        success = run_training(config_path, gpus, epochs)
        if not success:
            log.error("Training failed for %s. Skipping eval.", model_name)
            continue

        best_model = ablation_dir / "model" / "best_accuracy"
        for split in ("val", "test"):
            run_evaluation(best_model, f"{model_name}_{split}", split)

        log.info("Ablation B [%s] done.", dict_label)


# ---------------------------------------------------------------------------
# Ablation C — Data Augmentation
# ---------------------------------------------------------------------------

def ablation_augmentation(gpus: str, epochs: int) -> None:
    """
    Compare training with and without RecAug (PaddleOCR's text augmentation).

    RecAug applies random distortions, rotations, and colour jitter.
    On this small corpus it may help generalisation or cause overfitting —
    this ablation quantifies which effect dominates.
    """
    log.info("=== Ablation C: Data Augmentation ===")
    base_cfg = load_base_config()

    for use_aug in [True, False]:
        aug_label = "with_aug" if use_aug else "no_aug"
        ablation_dir = Path("experiments/ablation/augmentation") / aug_label
        ablation_dir.mkdir(parents=True, exist_ok=True)

        cfg = yaml.safe_load(yaml.dump(base_cfg))
        cfg["Global"]["save_model_dir"] = str(ablation_dir / "model")

        if not use_aug:
            # Remove RecAug from the transforms list
            transforms = cfg["Train"]["dataset"]["transforms"]
            cfg["Train"]["dataset"]["transforms"] = [
                t for t in transforms if "RecAug" not in t
            ]

        config_path = ablation_dir / "config.yml"
        save_config(cfg, config_path)

        model_name = f"ablation_aug_{aug_label}"
        success = run_training(config_path, gpus, epochs)
        if not success:
            log.error("Training failed for %s. Skipping eval.", model_name)
            continue

        best_model = ablation_dir / "model" / "best_accuracy"
        for split in ("val", "test"):
            run_evaluation(best_model, f"{model_name}_{split}", split)

        log.info("Ablation C [%s] done.", aug_label)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

ABLATION_MAP = {
    "data_size": ablation_data_size,
    "dictionary": ablation_dictionary,
    "augmentation": ablation_augmentation,
}


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Run structured ablation studies for Yorùbá OCR fine-tuning."
    )
    parser.add_argument(
        "--ablation",
        type=str,
        default="all",
        choices=["all", "data_size", "dictionary", "augmentation"],
        help="Which ablation to run.",
    )
    parser.add_argument(
        "--gpus",
        type=str,
        default="0",
        help="GPU IDs for training.",
    )
    parser.add_argument(
        "--epochs",
        type=int,
        default=100,
        help="Epochs per ablation run. Use a smaller value for quick testing.",
    )
    return parser.parse_args()


def main() -> None:
    """Dispatch to the requested ablation(s)."""
    args = parse_args()

    to_run = list(ABLATION_MAP.keys()) if args.ablation == "all" else [args.ablation]

    for name in to_run:
        log.info("Starting ablation: %s", name)
        ABLATION_MAP[name](args.gpus, args.epochs)

    log.info("All ablations complete. Results in %s", RESULTS_CSV)


if __name__ == "__main__":
    main()
