"""
Run PaddleOCR recognition fine-tuning with reproducible metadata.

This wrapper delegates the actual training loop to upstream
``PaddleOCR/tools/train.py`` and records the command, environment, config, and
timing under ``results/tables/train_run.json``. It does not modify the dataset.

Usage:
    python scripts/train_paddleocr_recognition.py \
        --config configs/paddleocr_yoruba_rec.yml \
        --paddle-dir PaddleOCR \
        --gpus 0
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path


def parse_args() -> argparse.Namespace:
    """Parse CLI arguments."""
    parser = argparse.ArgumentParser(description="Train PaddleOCR recognition model.")
    parser.add_argument(
        "--config",
        type=Path,
        default=Path("configs/paddleocr_yoruba_rec.yml"),
        help="PaddleOCR recognition YAML generated by 03_generate_config.py.",
    )
    parser.add_argument(
        "--paddle-dir",
        type=Path,
        default=Path("PaddleOCR"),
        help="Local clone of PaddleOCR containing tools/train.py.",
    )
    parser.add_argument(
        "--gpus",
        default="0",
        help="CUDA_VISIBLE_DEVICES value for GPU training. Ignored with --cpu.",
    )
    parser.add_argument(
        "--cpu",
        action="store_true",
        help="Run without setting CUDA_VISIBLE_DEVICES.",
    )
    parser.add_argument(
        "--resume",
        action="store_true",
        help="Leave config checkpoints untouched and let PaddleOCR resume if configured.",
    )
    parser.add_argument(
        "--log-file",
        type=Path,
        default=Path("results/tables/train_run.json"),
        help="Path for run metadata JSON.",
    )
    return parser.parse_args()


def git_sha() -> str | None:
    """Return the current short git SHA when available."""
    try:
        out = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            capture_output=True,
            text=True,
            timeout=3,
            check=False,
        )
        return out.stdout.strip() if out.returncode == 0 else None
    except (OSError, subprocess.TimeoutExpired):
        return None


def main() -> None:
    """Launch PaddleOCR training and persist metadata."""
    args = parse_args()
    root = Path.cwd()
    config = args.config.resolve()
    train_py = (args.paddle_dir / "tools" / "train.py").resolve()

    if not config.is_file():
        raise FileNotFoundError(f"Missing config: {config}")
    if not train_py.is_file():
        raise FileNotFoundError(
            f"Missing PaddleOCR trainer: {train_py}. Clone PaddleOCR first."
        )

    env = os.environ.copy()
    if args.cpu:
        env.pop("CUDA_VISIBLE_DEVICES", None)
    else:
        env["CUDA_VISIBLE_DEVICES"] = str(args.gpus)
    env.setdefault("FLAGS_allocator_strategy", "auto_growth")
    env.setdefault("PYTHONUNBUFFERED", "1")

    cmd = [sys.executable, str(train_py), "-c", str(config)]
    started = datetime.now(timezone.utc)
    start = time.time()
    proc = subprocess.run(cmd, cwd=root, env=env, check=False)
    ended = datetime.now(timezone.utc)

    payload = {
        "stage": "train_paddleocr_recognition",
        "started_at": started.isoformat(),
        "ended_at": ended.isoformat(),
        "duration_seconds": round(time.time() - start, 3),
        "returncode": proc.returncode,
        "command": cmd,
        "cwd": str(root),
        "git_sha": git_sha(),
        "config": str(config),
        "paddle_dir": str(args.paddle_dir.resolve()),
        "cpu": bool(args.cpu),
        "gpus": None if args.cpu else str(args.gpus),
        "resume": bool(args.resume),
    }
    args.log_file.parent.mkdir(parents=True, exist_ok=True)
    args.log_file.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")

    if proc.returncode != 0:
        raise SystemExit(proc.returncode)


if __name__ == "__main__":
    main()
